# SPDX-FileCopyrightText: 2020 The HedgeDoc developers (see AUTHORS file)
#
# SPDX-License-Identifier: AGPL-3.0-only

name: build

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the main branch of react-client and deploy it
    steps:
      - name: Install required moreutils
        run: sudo apt-get install moreutils gzip -yqq
      - name: Checkout react-client repository
        uses: actions/checkout@v2
        with:
          repository: 'hedgedoc/react-client'
          lfs: true
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache node_modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline
      - name: Get current commit hash
        id: get-commit-hash
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"
      
      - name: Change branding url
        run: jq '.branding.logo = "/img/acme.png"' public/api/v2/config | sponge public/api/v2/config
      - name: Write commit hash into version file
        run: jq '.version = "dev-${{ steps.get-commit-hash.outputs.sha }}"' src/version.json | sponge src/version.json
      - name: Correct source code url
        run: jq '.sourceCodeUrl = "https://github.com/hedgedoc/react-client/tree/${{ steps.get-commit-hash.outputs.sha }}/"' src/version.json | sponge src/version.json
      - name: Correct issue tracker url
        run: jq '.issueTrackerUrl = "https://github.com/hedgedoc/react-client/issues"' src/version.json | sponge src/version.json
      - name: Remove backend github URLs
        run: jq '. |= del(.version.sourceCodeUrl, .version.issueTrackerUrl)' public/api/v2/config | sponge public/api/v2/config
      - name: Update banner text
        run: jq '.banner.text = "ui-demo instance without backend for commit ${{ steps.get-commit-hash.outputs.sha }}"' public/api/v2/config | sponge public/api/v2/config
      
      - name: Create cname file
        run: echo -e "ui-test.hedgedoc.org\nui-test.hedgedoc.net\n" > public/CNAME
      
      - name: Build project
        run: yarn analyze
      - name: Fix 404 problem
        run: ln -s index.html 404.html
        working-directory: build
      - name: Compress stats.json
        run: gzip build/stats.json
      - name: Deploy to GitHub Pages Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
